/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Sousinho (https://sketchfab.com/sousinho)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/scifi-desk-d4a09022a8874ae6bdc44b3e42a6ea6c
Title: SciFi Desk
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const  ProjectsTable = (props) => {
  const { nodes, materials } = useGLTF('/models/scifi_desk.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_desk_T_desk_0.geometry}
          material={materials.T_desk}
          position={[317.432, -202.959, 72.096]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={150}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/scifi_desk.glb')
export default ProjectsTable