/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Théo Richard (https://sketchfab.com/theorichard)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/desk-light-4d203243ad614ecdbd9e6195a12dc8f2
Title: Desk Light
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'


const ProjectsLamp = (props) => {
  const { nodes, materials } = useGLTF('/models/desk_light.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['desk-light_desk-light_0'].geometry}
        material={materials['desk-light']}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/desk_light.glb')
export default ProjectsLamp