/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Jamesley (https://sketchfab.com/jamesley55)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rgb-keyboard-and-mouse-df00ce3e66dc4b75a5f9b49c2e6b1406
Title: RGB Keyboard and Mouse
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const ProjectsKeyboard = (props) => {
  const { nodes, materials } = useGLTF('/models/rgb_keyboard_and_mouse.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.525}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[34.301, -13.774, 127.746]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Mouse_under_body_Mouse_under_body_0.geometry}
              material={materials.Mouse_under_body}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Mouse_under_body_Mouse_touch_0.geometry}
              material={materials.Mouse_touch}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Mouse_under_body_Mouse_body_0.geometry}
              material={materials.Mouse_body}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Mouse_under_body_Mouse_below_0.geometry}
              material={materials.Mouse_below}
            />
          </group>
          <group position={[32.634, -6.429, 61.792]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Keyboard_Keyboard_0.geometry}
              material={materials.Keyboard}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Keyboard_Key_0.geometry}
              material={materials.material}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mouse_wheel_Scroll_wheel_0.geometry}
            material={materials.Scroll_wheel}
            position={[34.301, -5.521, 110.012]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={100}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/rgb_keyboard_and_mouse.glb')
export default ProjectsKeyboard